#ifndef __BOOT_LOGO_H__
#define __BOOT_LOGO_H__

#include "lvgl.h"

/* Defined in boot_logo.c, generated by LVGL's own image-conversion script
 * (managed_components/lvgl__lvgl/scripts/LVGLImage.py) from the 240x240
 * source PNG -- regenerate that file (same script, same options) rather
 * than hand-editing it if the logo artwork ever changes. See
 * rgb_tile_show_boot_logo() for how it's displayed. */
extern const lv_image_dsc_t boot_logo;

#endif
